import { Poppins, Inter } from "next/font/google";
import "./globals.css";
import Topbar from "@/components/Topbar";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css'; // সিএসএস ইমপোর্ট করা না থাকলে এটি যুক্ত করে নিন
import MenuBar from "@/components/MenuBar";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html 
      suppressHydrationWarning
      data-theme="light"
      lang="en"
      className={`${poppins.variable} ${inter.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <Topbar/>
        <Navbar/>
        <MenuBar/>
        {children}
        <Footer/>
        <ToastContainer 
  position="top-center" 
  autoClose={3000} 
  style={{ 
    width: "max-content", 
    maxWidth: "75vw",
    left: "50%", 
    transform: "translateX(-50%)", 
    marginTop: "10px", 
    display: "flex",
    justifyContent: "center"
  }} 
/>
      </body>
    </html>
  );
}